# Generated by Django 6.0.6 on 2026-07-05 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendezvous', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RappelModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_rappel', models.CharField(choices=[('24h', 'Rappel 24 heures avant'), ('1h', 'Rappel 1 heure avant')], max_length=10)),
                ('email_envoye', models.EmailField(max_length=254)),
                ('statut', models.CharField(choices=[('envoye', 'Envoyé'), ('echoue', 'Échoué')], default='envoye', max_length=10)),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('rendezvous', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rappels', to='rendezvous.rendezvousmodel')),
            ],
            options={
                'verbose_name': 'Rappel',
                'verbose_name_plural': 'Rappels',
                'db_table': 'rappels',
                'unique_together': {('rendezvous', 'type_rappel')},
            },
        ),
    ]
