# Generated by Django 6.0.6 on 2026-07-06 18:01

import rendezvous.infrastructure.django_models.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendezvous', '0003_tokenresetmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateurmodel',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=rendezvous.infrastructure.django_models.models.chemin_photo_profil, verbose_name='Photo de profil'),
        ),
    ]
