# Generated by Django 6.0.6 on 2026-07-06 18:09

import django.db.models.deletion
import rendezvous.infrastructure.django_models.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendezvous', '0004_utilisateurmodel_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeOtpModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=rendezvous.infrastructure.django_models.models.generer_code_otp, max_length=6)),
                ('date_expiration', models.DateTimeField()),
                ('utilise', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes_otp', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Code OTP',
                'db_table': 'codes_otp',
            },
        ),
    ]
