# Generated by Django 6.0.6 on 2026-07-06 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendezvous', '0005_codeotpmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateurmodel',
            name='deux_fa_active',
            field=models.BooleanField(default=False, verbose_name='2FA activée'),
        ),
    ]
