# Generated by Django 6.0.6 on 2026-07-17 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendezvous', '0006_utilisateurmodel_deux_fa_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvousmodel',
            name='paiement_autorise',
            field=models.BooleanField(default=False, verbose_name='Paiement autorisé'),
        ),
        migrations.AddField(
            model_name='rendezvousmodel',
            name='prix_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix au moment du RDV'),
        ),
        migrations.CreateModel(
            name='ServiceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duree_minutes', models.PositiveIntegerField(default=30)),
                ('est_actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='rendezvous.entreprisemodel')),
            ],
            options={
                'verbose_name': 'Service',
                'db_table': 'services',
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='personnelmodel',
            name='services_proposes',
            field=models.ManyToManyField(blank=True, related_name='personnels', to='rendezvous.servicemodel'),
        ),
        migrations.AddField(
            model_name='rendezvousmodel',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rendezvous', to='rendezvous.servicemodel'),
        ),
    ]
