# Generated by Django 6.0.6 on 2026-07-19 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendezvous', '0007_rendezvousmodel_paiement_autorise_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_conversation', models.CharField(choices=[('client_personnel', 'Client ↔ Personnel'), ('admin_personnel', 'Admin ↔ Personnel')], default='client_personnel', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='rendezvous.administrateurmodel')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='rendezvous.clientmodel')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='rendezvous.personnelmodel')),
                ('rdv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='rendezvous.rendezvousmodel')),
            ],
            options={
                'verbose_name': 'Conversation',
                'db_table': 'conversations',
                'ordering': ['-date_modification'],
                'unique_together': {('rdv', 'client', 'personnel')},
            },
        ),
        migrations.CreateModel(
            name='MessageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('est_lu', models.BooleanField(default=False)),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='rendezvous.conversationmodel')),
                ('expediteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_envoyes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message',
                'db_table': 'messages',
                'ordering': ['date_envoi'],
            },
        ),
    ]
