"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

"""
=============================================================
  config/settings.py
  Configuration principale du projet Django
=============================================================
"""
from pathlib import Path
from datetime import timedelta

# BASE_DIR = le dossier racine de ton projet (rendezvous_project/)
BASE_DIR = Path(__file__).resolve().parent.parent

# Clé secrète Django — ne jamais la partager en production
SECRET_KEY = 'django-insecure-change-this-in-production'

# True pendant le développement, False en production
DEBUG = True

ALLOWED_HOSTS = ['*']

# =============================================================
#   APPLICATIONS INSTALLÉES
# =============================================================
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Bibliothèques tierces
    'rest_framework',            # Pour construire notre API REST
    'rest_framework_simplejwt',  # Pour l'authentification par tokens JWT
    'corsheaders',               # Pour autoriser le frontend à appeler l'API
    'django_filters',            # Pour filtrer les listes facilement
     # ← Commenter ou supprimer cette ligne
    'rest_framework_simplejwt.token_blacklist',
    'drf_yasg',    # ← à la place de drf_spectacular
    'django_celery_beat',   # ← ajouter pour les planifications des messages automatiques

    # Notre unique application
    'rendezvous',
]

MIDDLEWARE = [
    # corsheaders DOIT être en premier
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
        # ← Commenter cette ligne temporairement
    'rendezvous.presentation.middleware.SecurityMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# =============================================================
#   BASE DE DONNÉES POSTGRESQL
# =============================================================
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'rendezvous_db',   # Nom de la base créée à l'étape 2
        'USER': 'postgres',
        'PASSWORD': '123',          # Ton mot de passe local
        'HOST': 'localhost',
        'PORT': '5432', #'5433pip install drf-spectacular',
    }
}

# =============================================================
#   MODÈLE UTILISATEUR PERSONNALISÉ
#   On remplace le User Django par défaut par le nôtre
# =============================================================
AUTH_USER_MODEL = 'rendezvous.UtilisateurModel'

# =============================================================
#   CONFIGURATION API REST
# =============================================================
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
    'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 100,
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    #'EXCEPTION_HANDLER': 'rendezvous.presentation.exceptions_handler.custom_exception_handler',
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon':        '100/minute',
        'user':        '200/minute',
        'login':       '10/minute',    # ← Ce scope manquait
        'inscription': '5/hour',
    },
}

# =============================================================
#   TOKENS JWT
# =============================================================
SIMPLE_JWT = {
    # Le token d'accès expire après 2 heures
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=2),
    # Le token de rafraîchissement expire après 7 jours
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    # Un nouveau refresh token est généré à chaque utilisation
    'ROTATE_REFRESH_TOKENS': True,
    # Format dans les en-têtes HTTP : "Authorization: Bearer <token>"
    'AUTH_HEADER_TYPES': ('Bearer',),
    'ALGORITHM':              'HS256',
    # ← Commenter cette ligne
    'BLACKLIST_AFTER_ROTATION': True,

}

# Autoriser toutes les origines (en prod, lister les domaines autorisés)
CORS_ALLOW_ALL_ORIGINS = True

# =============================================================
#   FICHIERS STATIQUES ET MÉDIAS
# =============================================================
STATIC_URL = '/static/'
MEDIA_URL = '/media/'
# Les fichiers uploadés sont stockés dans rendezvous_project/media/
MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
LANGUAGE_CODE = 'fr-fr'
TIME_ZONE = 'Africa/Douala'
USE_I18N = True
USE_TZ = True


# =============================================================
#   DOCUMENTATION API — Swagger / OpenAPI
# =============================================================
SPECTACULAR_SETTINGS = {
    'TITLE': 'API Rendez-vous',
    'DESCRIPTION': '''
## API de gestion de rendez-vous

### Authentification
Toutes les routes (sauf inscription et login) nécessitent un token JWT.

1. Connectez-vous via `POST /api/auth/login/`
2. Copiez le token `access` reçu
3. Cliquez sur **Authorize** en haut à droite
4. Entrez : `Bearer votre_token_ici`

### Rôles
- **client** : prendre des RDV, payer
- **admin** : confirmer/refuser les RDV, gérer les entreprises
- **personnel** : gérer les créneaux
    ''',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,

    # Ajouter le bouton "Authorize" pour le JWT
    'SECURITY': [{'BearerAuth': []}],
    'COMPONENTS': {
        'securitySchemes': {
            'BearerAuth': {
                'type': 'http',
                'scheme': 'bearer',
                'bearerFormat': 'JWT',
            }
        }
    },

    # Grouper les endpoints par tag
    'TAGS': [
        {'name': 'auth',           'description': 'Authentification et sécurité'},
        {'name': 'users',          'description': 'Gestion des utilisateurs'},
        {'name': 'entreprises',    'description': 'Entreprises et domaines'},
        {'name': 'creneaux',       'description': 'Créneaux horaires'},
        {'name': 'rendezvous',     'description': 'Prise et gestion des RDV'},
        {'name': 'paiements',      'description': 'Paiements'},
        {'name': 'notifications',  'description': 'Notifications'},
    ],
}


STATIC_ROOT = BASE_DIR / 'staticfiles'




# =============================================================
#   CONFIGURATION EMAIL
# =============================================================

EMAIL_BACKEND       = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST          = 'smtp.mail.me.com'
EMAIL_PORT          = 587
EMAIL_USE_TLS       = True
EMAIL_HOST_USER     = 'afizanoura@icloud.com'
EMAIL_HOST_PASSWORD = 'ayoc-eyif-jzrx-junu'
DEFAULT_FROM_EMAIL  = 'RendezVous Pro <afizanoura@icloud.com>'









# ── Django-Q (remplace Celery+Redis) ─────────────────────────
INSTALLED_APPS += ['django_q']

Q_CLUSTER = {
    'name':       'rdv_pro',
    'workers':    2,
    'recycle':    500,
    'timeout':    60,
    'compress':   True,
    'save_limit': 250,
    'queue_limit': 500,
    'cpu_affinity': 1,
    'label':      'Django Q',
    'orm':        'default',   # ← utilise PostgreSQL, pas Redis
}

import os
MEDIA_URL  = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')